In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv("CKD.csv")
dataset

age         bp sg   al   su     rbc        pc         pcc  \
0     2.000000  76.459948  c  3.0  0.0  normal  abnormal  notpresent   
1     3.000000  76.459948  c  2.0  0.0  normal    normal  notpresent   
2     4.000000  76.459948  a  1.0  0.0  normal    normal  notpresent   
3     5.000000  76.459948  d  1.0  0.0  normal    normal  notpresent   
4     5.000000  50.000000  c  0.0  0.0  normal    normal  notpresent   
..         ...        ... ..  ...  ...     ...       ...         ...   
394  51.492308  70.000000  a  0.0  0.0  normal    normal  notpresent   
395  51.492308  70.000000  c  0.0  2.0  normal    normal  notpresent   
396  51.492308  70.000000  c  3.0  0.0  normal    normal  notpresent   
397  51.492308  90.000000  a  0.0  0.0  normal    normal  notpresent   
398  51.492308  80.000000  a  0.0  0.0  normal    normal  notpresent   

             ba         bgr  ...        pcv            wc        rc  htn   dm  \
0    notpresent  148.112676  ...  38.868902   8408.191126  4.705597   no   no   
1    notpresent  148.112676  ...  34.000000  12300.000000  4.705597   no   no   
2    notpresent   99.000000  ...  34.000000   8408.191126  4.705597   no   no   
3    notpresent  148.112676  ...  38.868902   8408.191126  4.705597   no   no   
4    notpresent  148.112676  ...  36.000000  12400.000000  4.705597   no   no   
..          ...         ...  ...        ...           ...       ...  ...  ...   
394  notpresent  219.000000  ...  37.000000   9800.000000  4.400000   no   no   
395  notpresent  220.000000  ...  27.000000   8408.191126  4.705597  yes  yes   
396  notpresent  110.000000  ...  26.000000   9200.000000  3.400000  yes  yes   
397  notpresent  207.000000  ...  38.868902   8408.191126  4.705597  yes  yes   
398  notpresent  100.000000  ...  53.000000   8500.000000  4.900000   no   no   

     cad  appet    pe  ane classification  
0     no    yes   yes   no            yes  
1     no    yes  poor   no            yes  
2     no    yes  poor   no            yes  
3     no    yes  poor  yes            yes  
4     no    yes  poor   no            yes  
..   ...    ...   ...  ...            ...  
394   no    yes  poor   no            yes  
395   no    yes  poor  yes            yes  
396   no   poor  poor   no            yes  
397   no    yes  poor  yes            yes  
398   no    yes  poor   no             no  

[399 rows x 25 columns]

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

age         bp   al   su         bgr          bu        sc  \
0     2.000000  76.459948  3.0  0.0  148.112676   57.482105  3.077356   
1     3.000000  76.459948  2.0  0.0  148.112676   22.000000  0.700000   
2     4.000000  76.459948  1.0  0.0   99.000000   23.000000  0.600000   
3     5.000000  76.459948  1.0  0.0  148.112676   16.000000  0.700000   
4     5.000000  50.000000  0.0  0.0  148.112676   25.000000  0.600000   
..         ...        ...  ...  ...         ...         ...       ...   
394  51.492308  70.000000  0.0  0.0  219.000000   36.000000  1.300000   
395  51.492308  70.000000  0.0  2.0  220.000000   68.000000  2.800000   
396  51.492308  70.000000  3.0  0.0  110.000000  115.000000  6.000000   
397  51.492308  90.000000  0.0  0.0  207.000000   80.000000  6.800000   
398  51.492308  80.000000  0.0  0.0  100.000000   49.000000  1.000000   

            sod       pot       hrmo  ...  pc_normal  pcc_present  ba_present  \
0    137.528754  4.627244  12.518156  ...      False        False       False   
1    137.528754  4.627244  10.700000  ...       True        False       False   
2    138.000000  4.400000  12.000000  ...       True        False       False   
3    138.000000  3.200000   8.100000  ...       True        False       False   
4    137.528754  4.627244  11.800000  ...       True        False       False   
..          ...       ...        ...  ...        ...          ...         ...   
394  139.000000  3.700000  12.500000  ...       True        False       False   
395  137.528754  4.627244   8.700000  ...       True        False       False   
396  134.000000  2.700000   9.100000  ...       True        False       False   
397  142.000000  5.500000   8.500000  ...       True        False       False   
398  140.000000  5.000000  16.300000  ...       True        False       False   

     htn_yes  dm_yes  cad_yes  appet_yes  pe_yes  ane_yes  classification_yes  
0      False   False    False       True    True    False                True  
1      False   False    False       True   False    False                True  
2      False   False    False       True   False    False                True  
3      False   False    False       True   False     True                True  
4      False   False    False       True   False    False                True  
..       ...     ...      ...        ...     ...      ...                 ...  
394    False   False    False       True   False    False                True  
395     True    True    False       True   False     True                True  
396     True    True    False      False   False    False                True  
397     True    True    False       True   False     True                True  
398    False   False    False       True   False    False               False  

[399 rows x 28 columns]

In [4]:
print(dataset.columns)

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')


In [5]:
dataset["classification_yes"].value_counts()

classification_yes
True     249
False    150
Name: count, dtype: int64

In [6]:
indep=dataset[["age","bp","al","su","bgr","bu","sc","sod","pot","hrmo","pcv","wc","rc","sg_b","sg_c","sg_e","rbc_normal","pc_normal","pcc_present","ba_present","htn_yes","dm_yes","cad_yes","appet_yes","pe_yes","ane_yes"]]
dep=dataset["classification_yes"]


In [7]:
indep.shape

(399, 26)

In [8]:
dep

0       True
1       True
2       True
3       True
4       True
       ...  
394     True
395     True
396     True
397     True
398    False
Name: classification_yes, Length: 399, dtype: bool

In [9]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [10]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)              
print(clf_report)
print(cm)

              precision    recall  f1-score   support

       False       0.68      0.98      0.80        51
        True       0.98      0.71      0.82        82

    accuracy                           0.81       133
   macro avg       0.83      0.84      0.81       133
weighted avg       0.87      0.81      0.81       133

[[50  1]
 [24 58]]


In [11]:
from sklearn.naive_bayes import BernoulliNB
classifier = BernoulliNB()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)              
print(clf_report)
print(cm)

              precision    recall  f1-score   support

       False       0.86      1.00      0.93        51
        True       1.00      0.90      0.95        82

    accuracy                           0.94       133
   macro avg       0.93      0.95      0.94       133
weighted avg       0.95      0.94      0.94       133

[[51  0]
 [ 8 74]]


In [12]:
from sklearn.naive_bayes import ComplementNB
classifier =ComplementNB()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)              
print(clf_report)
print(cm)

              precision    recall  f1-score   support

       False       0.67      0.98      0.79        51
        True       0.98      0.70      0.81        82

    accuracy                           0.80       133
   macro avg       0.82      0.84      0.80       133
weighted avg       0.86      0.80      0.81       133

[[50  1]
 [25 57]]


In [13]:
#Performing Grid search for BernoulliNB to see if the accuracy can be improved further with different parameters

In [19]:
#http://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.BernoulliNB.html#sklearn.naive_bayes.BernoulliNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.model_selection import GridSearchCV
param_grid = {'alpha':[1.0, 2.0, 3.0],'binarize':[0.0, 1.0, 2.0],'fit_prior':[True,False],'class_prior':[None],'force_alpha':[True] } 
grid = GridSearchCV(BernoulliNB(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted')    
# fitting the model for grid search 
grid.fit(X_train, y_train) 

Fitting 5 folds for each of 18 candidates, totalling 90 fits


GridSearchCV(estimator=BernoulliNB(), n_jobs=-1,
             param_grid={'alpha': [1.0, 2.0, 3.0], 'binarize': [0.0, 1.0, 2.0],
                         'class_prior': [None], 'fit_prior': [True, False],
                         'force_alpha': [True]},
             scoring='f1_weighted', verbose=3)

In [20]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test) 
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)

# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [21]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'alpha': 1.0, 'binarize': 0.0, 'class_prior': None, 'fit_prior': True, 'force_alpha': True}: 0.940494593126172


In [22]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[51  0]
 [ 8 74]]


In [23]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

       False       0.86      1.00      0.93        51
        True       1.00      0.90      0.95        82

    accuracy                           0.94       133
   macro avg       0.93      0.95      0.94       133
weighted avg       0.95      0.94      0.94       133



In [24]:
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

np.float64(0.9832615973218556)

In [25]:
table=pd.DataFrame.from_dict(re)

In [27]:
age_input=float(input("Age:"))
bp=float(input("bp:"))
al=int(input("al:"))
su=int(input("su:"))
bgr=int(input("bgr:"))
bu=int(input("bu:"))
sc=float(input("sc:"))
sod=float(input("sod:"))
pot=float(input("pot:"))
hrmo=float(input("hrmo:"))
pcv=float(input("pcv:"))
wc=float(input("wc:"))
rc=float(input("rc:"))
sg_b=int(input("sg_b:0 or 1"))
sg_c=int(input("sg_c: 0 or 1"))
sg_e=int(input("sg_e: 0 or 1"))
rbc_normal=int(input("rbc_normal: 0 or 1"))
pc_normal=int(input("pc_normal:0 or 1"))
pcc_present=int(input("pcc_present:0 or 1"))
ba_present=int(input("ba_present:0 or 1"))
htn_yes=int(input("htn_yes:0 or 1"))
dm_yes=int(input("dm_yes:0 or 1"))
cad_yes=int(input("cad_yes: 0 or 1:"))
appet_yes=int(input("appet_yes: 0 or 1:"))
pe_yes=int(input("pe_yes: 0 or 1:"))
ane_yes=int(input("ane_yes: 0 or 1:"))


Age: 41
bp: 122
al: 3
su: 2
bgr: 219
bu: 115
sc: 1.3
sod: 134
pot: 4.4
hrmo: 12
pcv: 34
wc: 8600
rc: 4.8
sg_b:0 or 1 1
sg_c: 0 or 1 0
sg_e: 0 or 1 1
rbc_normal: 0 or 1 1
pc_normal:0 or 1 1
pcc_present:0 or 1 1
ba_present:0 or 1 1
htn_yes:0 or 1 1
dm_yes:0 or 1 0
cad_yes: 0 or 1: 1
appet_yes: 0 or 1: 0
pe_yes: 0 or 1: 0
ane_yes: 0 or 1: 1


In [32]:
Future_Prediction=grid.predict([[age_input,bp,al,su,bgr,bu,sc,sod,pot,hrmo,pcv,wc,rc,sg_b,sg_c,sg_e,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,pe_yes]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[ True]


C:\Users\gssan\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but BernoulliNB was fitted with feature names
  warnings.warn(
